spring.application.name=tp_backend

spring.datasource.url=jdbc:h2:mem:tpdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.h2.console.settings.web-allow-others=true

app.bootstrap.admin.username=admin
app.bootstrap.admin.email=admin@shop.local
app.bootstrap.admin.password=admin123
app.bootstrap.seed-demo-data=true

app.jwt.secret=ReplaceThisWithAtLeast32CharactersSecretKeyForJwtSigning123
app.jwt.expiration-ms=86400000
